### ISSUE TITLE
Reg UserName and Password while deploying to PCF in the cfConfig

### ISSUE THREAD

**Issue by sujittripathy** [pivotalservices/ya-cf-app-gradle-plugin#21]
Hi,
Is there any way the username (ccUser) and password (ccPassword) can be remembered so, that while using cf-push no need to provide username and password each time and will be much convenient for the developer.

**Comment by bijukunjummen** [comment]
I am not entirely convinced about doing this @sujittripathy - the plugin is expected to be used via a CI box right where leaving creds around which may get picked up by jobs run in parallel is a real risk and I have personally faced this with `cf` command line tools which store the creds. Is your use case for doing push manually from your machine?

**Comment by sujittripathy** [comment]
Yeah @bijukunjummen. I joined newly a project where PCF is being used and its using cf-app plugin and configuring setup in cfConfig to push to PCF dev environment from local with use of `cf-push` which need user name, password, space etc.. to login and push to dev environment which is same as `cf` cli. I am not sure if this is the right way of setup to push the local build to PCF dev env, however it's big inconvenience to provide user id/pwd every time. I am not finding much detail documentation around the plugin, though it has some nice features:). It would be nice if the parameters taken from user OS env variable which can be setup once in developer machine.

**Comment by bijukunjummen** [comment]
See if this works for you @sujittripathy - if you use https://github.com/pivotalservices/ya-cf-app-gradle-plugin/releases/tag/v2.2.0-rc.6 version of the plugin, then you can specify environment variables which should override any creds in the configuration, this way you have to specify it just once:

```
export CF_CCUSER=admin
export CF_CCPASSWORD=admin
./gradlew cf-push
```

**Comment by sujittripathy** [comment]
@bijukunjummen I tried this but didn't work. Getting null pointer. below is the exception stack trace 
```
Caused by: java.lang.NullPointerException: ccUser
        at io.pivotal.services.plugin.ImmutableCfProperties$Builder.ccUser(ImmutableCfProperties.java:1804)
        at io.pivotal.services.plugin.CfPropertiesMapper.getProperties(CfPropertiesMapper.java:57)
        at io.pivotal.services.plugin.tasks.AbstractCfTask.getCfProperties(AbstractCfTask.java:65)
        at io.pivotal.services.plugin.tasks.CfPushTask_Decorated.getCfProperties(Unknown Source)
        at io.pivotal.services.plugin.tasks.CfPushTask.push(CfPushTask.java:22)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:692)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:675)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:115)
```

**Comment by bijukunjummen** [comment]
Strange, you may be on a old version of the plugin, I just checked and it appears to work. Do ensure that you are on 2.2.0-rc.6 version of the plugin which has this functionality:

```
buildscript {
	ext {
		cfAppVersion = '2.2.0-rc.6'
	}
	repositories {
		mavenCentral()
		maven { url "https://oss.sonatype.org/content/repositories/releases" }
		maven { url "https://repo.spring.io/release" }
	}
	dependencies {
		classpath("com.github.pivotalservices:ya-cf-app-gradle-plugin:${cfAppVersion}")
	}
}

apply plugin: 'cf-app'
```

OR

```
plugins {
	id "com.github.pivotalservices.cf-app" version "2.2.0-rc.6"
}
```

**Comment by sujittripathy** [comment]
That's correct. The plugin was old and when I updated to `2.2.0-rc.6` version, it worked. Appreciate your help @bijukunjummen 👍
